name: "Auto Commit Action"
description: "Automatically commits and pushes changes if found."
inputs:
  github_token:
    description: "GitHub token to authenticate the push"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check for Changes
      shell: bash
      run: |
        if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected. Enter commit message:"
            read commit_message

            git config --global user.email "developersharma1999@gmail.com"
            git config --global user.name "nerdlyDev"

            git add .
            git commit -m "$commit_message"
            git push "https://x-access-token:${{ inputs.github_token }}@github.com/${{ github.repository }}.git" HEAD:main
        else
            echo "No changes detected."
